# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: &default
  # adapter: mysql2
  adapter: jdbcmysql
  encoding: utf8
  reconnect: true
  database: fnnny_development
  pool: 2
  username: root
  password: 
  host: 127.0.0.1
  socket: /usr/local/var/mysql/mysql.sock
  port: 3306

test: &test
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: fnnny_test

production:
  <<: *default
  database: fnnny_production
  pool: 10
